import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:fitnesslocator/Admin/LoginAdmin.dart';

const mainwallpaper = 'https://wallpapercave.com/dwp2x/wp10509084.jpg';

String currentloginstate = '';

const LoginUserWallpaper = 'https://wallpapercave.com/wp/wp2356164.jpg';

const LoginOwnerWallpaper =
    'https://images.pexels.com/photos/1624438/pexels-photo-1624438.jpeg?auto=compress&cs=tinysrgb&w=1600';

var citylist = List.from(_Cities);
// var FitnessTypes = List.from(_FitnessType);
// var fitnessGendertype = List.from(_GenderType);

// List<String> _FitnessType = <String>[
//   'Gym',
//   'Cricket Club',
//   'Football Club',
//   'Yoga Center',
//   'Boxing Club',
//   'Tennis',
//   'Karate',
//   'Table tennis Club',
//   'BasketBall Club',
//   'Swimming'
// ];
// List<String> _GenderType = <String>['Male', 'Female', 'Co'];

List<String> _Cities = <String>[
  'Karachi',
  'Lahore',
  'Faisalabad',
  'Rawalpindi',
  'Gujranwala',
  'Peshawar',
  'Multan',
  'Saidu Sharif',
  'Hyderabad City',
  'Islamabad',
  'Quetta',
  'Bahawalpur',
  'Sargodha',
  'Sialkot City',
  'Sukkur',
  'Larkana',
  'Chiniot',
  'Shekhupura',
  'Jhang City',
  'Dera Ghazi Khan',
  'Gujrat',
  'Rahimyar Khan',
  'Kasur',
  'Mardan',
  'Mingaora',
  'Nawabshah',
  'Sahiwal',
  'Mirpur Khas',
  'Okara',
  'Mandi Burewala',
  'Jacobabad',
  'Saddiqabad',
  'Kohat',
  'Muridke',
  'Muzaffargarh',
  'Khanpur',
  'Gojra',
  'Mandi Bahauddin',
  'Abbottabad',
  'Turbat',
  'Dadu',
  'Bahawalnagar',
  'Khuzdar',
  'Pakpattan',
  'Tando Allahyar',
  'Ahmadpur East',
  'Vihari',
  'Jaranwala',
  'New Mirpur',
  'Kamalia',
  'Kot Addu',
  'Nowshera',
  'Swabi',
  'Khushab',
  'Dera Ismail Khan',
  'Chaman',
  'Charsadda',
  'Kandhkot',
  'Chishtian',
  'Hasilpur',
  'Attock Khurd',
  'Muzaffarabad',
  'Mianwali',
  'Jalalpur Jattan',
  'Bhakkar',
  'Zhob',
  'Dipalpur',
  'Kharian',
  'Mian Channun',
  'Bhalwal',
  'Jamshoro',
  'Pattoki',
  'Harunabad',
  'Kahror Pakka',
  'Toba Tek Singh',
  'Samundri',
  'Shakargarh',
  'Sambrial',
  'Shujaabad',
  'Hujra Shah Muqim',
  'Kabirwala',
  'Mansehra',
  'Lala Musa',
  'Chunian',
  'Nankana Sahib',
  'Bannu',
  'Pasrur',
  'Timargara',
  'Parachinar',
  'Chenab Nagar',
  'Gwadar',
  'Abdul Hakim',
  'Hassan Abdal',
  'Tank',
  'Hangu',
  'Risalpur Cantonment',
  'Karak',
  'Kundian',
  'Umarkot',
  'Chitral',
  'Dainyor',
  'Kulachi',
  'Kalat',
  'Kotli',
  'Gilgit',
  'Narowal',
  'Khairpur Mir’s',
  'Khanewal',
  'Jhelum',
  'Haripur',
  'Shikarpur',
  'Rawala Kot',
  'Hafizabad',
  'Lodhran',
  'Malakand',
  'Attock City',
  'Batgram',
  'Matiari',
  'Ghotki',
  'Naushahro Firoz',
  'Alpurai',
  'Bagh',
  'Daggar',
  'Leiah',
  'Tando Muhammad Khan',
  'Chakwal',
  'Badin',
  'Lakki',
  'Rajanpur',
  'Dera Allahyar',
  'Shahdad Kot',
  'Pishin',
  'Sanghar',
  'Upper Dir',
  'Thatta',
  'Dera Murad Jamali',
  'Kohlu',
  'Mastung',
  'Dasu',
  'Athmuqam',
  'Loralai',
  'Barkhan',
  'Musa Khel Bazar',
  'Ziarat',
  'Gandava',
  'Sibi',
  'Dera Bugti',
  'Eidgah',
  'Uthal',
  'Khuzdar',
  'Chilas',
  'Panjgur',
  'Gakuch',
  'Qila Saifullah',
  'Kharan',
  'Aliabad',
  'Awaran',
  'Dalbandin'
];

DocumentSnapshot? gymOwnerconstant;
